version: '3'
networks:
  my_network_name:
    name: my_network_name
    external: false

services:
  mysql:
    image: 'bitnami/mysql:latest'
    container_name: mysql
    ports:
      - '3310:3306'
    volumes:
      - '/docker-entrypoint-initdb.d'
      - '/bitnami/mysql/data'
    environment: 
            MYSQL_ROOT_PASSWORD: <root_password>
            MYSQL_DATABASE: schedulefyi
            MYSQL_USER: schedulefyi
            MYSQL_PASSWORD: <schedulefyi_password>
    networks:
      - my_network_name

  flask:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flask_project
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 5002:5000
    networks:
      - my_network_name
