version: '3.7'
services:
  mysql:
    image: bitnami/mysql:latest
    container_name: mysql
    ports:
      - '3309:3306'
    volumes:
      - '/Applications/mamp/mysql/data'
    environment: 
            MYSQL_ROOT_PASSWORD: my_root_pwd
            MYSQL_DATABASE: schedulefyi
            MYSQL_USER: schedulefyi
            MYSQL_PASSWORD: schedulefyi_pwd

  flask:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flask
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 5001:5000
