version: '3.8'
services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    container_name: mysql_db
    ports:
      - '127.0.0.1:3309:3306'
    volumes:
      - '/Applications/mamp/mysql/data'
    environment: 
            MYSQL_ROOT_PASSWORD: cFa2807
            MYSQL_DATABASE: schedulefyi
            MYSQL_USER: schedulefyi
            MYSQL_PASSWORD: uN7LgrJtvN6H94Tm

  flask:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flask
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 5001:5000
